language: generic
services:
  - docker

before_install:
  - docker build -t kamiour/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kamiour/react-test npm test

after_success:
  - docker build -t kamiour/multi-client ./client
  - docker build -t kamiour/multi-server ./server
  - docker build -t kamiour/multi-worker ./worker
  - docker build -t kamiour/multi-nginx ./nginx
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Pushing images to Docker hub
  - docker push kamiour/multi-client
  - docker push kamiour/multi-server
  - docker push kamiour/multi-worker
  - docker push kamiour/multi-nginx
